### ISSUE TITLE
移动端缩放问题

### ISSUE THREAD

**Issue by lplusc** [ClosureTalk/closure-talk#10]
PC端或平板使用还好，在屏幕尺寸较小的手机上左半边的角色选择栏几乎占满整个屏幕且无法调整，希望后续能够适配移动端进行一定程度的缩放，或者可以收起左侧角色选择侧边栏

**Comment by logchan** [comment]
确实有匹配移动端的计划

最近工作终于忙完了，准备更新一波……

**Comment by logchan** [comment]
之前匹配了移动端，忘记回复了
