### ISSUE TITLE
生成图片时，图片高度可能会超过Canvas渲染上限，导致压缩图片

### ISSUE THREAD

**Issue by LinkiCangon** [ClosureTalk/closure-talk#13]
Canvas的渲染高度上限似乎是16384像素，超过这个高度后，屏幕捕捉便会将图片自动按比例压缩至16384像素内，导致清晰度降低。
不知道您是否可能会考虑在生成图片时检查一下图片的高度，并在，比如说，图片高度超过16000像素时将图片进行切分后下载？

我知道恐怕这是个很难会有人碰到的应用场景，但无奈我写得实在太长了。如果它能够比较简单地被解决的话，我希望您能满足一下这个小小的需求。非常感谢！

**Comment by logchan** [comment]
了解，下周看看

**Comment by logchan** [comment]
增加了可以在编辑对话时勾选【分割】的功能，截图时会自动在选择了【分割】的地方分开截图

**Comment by LinkiCangon** [comment]
> 增加了可以在编辑对话时勾选【分割】的功能，截图时会自动在选择了【分割】的地方分开截图

感谢老哥，老哥NB！
