### ISSUE TITLE
分割图片功能导致图片横纵比错乱

### ISSUE THREAD

**Issue by Walker-BJ99** [ClosureTalk/closure-talk#16]
如图所示

![image](https://user-images.githubusercontent.com/75510566/236504936-dfd293e6-d6d8-4642-943a-3d329ac9cf1c.png)

![image](https://user-images.githubusercontent.com/75510566/236505094-bdab17c3-eb76-478c-a65e-2b9bd60d3dd1.png)

**Comment by logchan** [comment]
请问是什么浏览器？能否分享一下代码json

**Comment by Walker-BJ99** [comment]
抱歉几天后才看到，使用的是Edge 113.0.1774.50（64位）
并且似乎任何文章使用了这个功能都会导致问题

**Comment by logchan** [comment]
已修复
