### ISSUE TITLE
关于在Json文件中添加自定义角色的问题

### ISSUE THREAD

**Issue by Richardoooo** [ClosureTalk/closure-talk#19]
就我所知，自定义角色是保存在**浏览器**里而并非**Json**中，

当你在浏览器中删除该角色，导入json后该角色的对话会变成自己的对话。

您能否把**自定义角色的数据**改为储存在json文件里，方便转移？

**Comment by Richardoooo** [comment]
补充：
刚刚和群友讨论时产生了歧义，这里的意思是把**自定义角色**放进**储存对话**的json文件中进行合并。

**Comment by logchan** [comment]
应该可行

**Comment by logchan** [comment]
已添加支持
