### ISSUE TITLE
建议在右键编辑内容的菜单中也同时提供“提交”或“确认”按钮

### ISSUE THREAD

**Issue by sctop** [ClosureTalk/closure-talk#20]
如题，这里描述的情况为：

![image](https://github.com/ClosureTalk/closure-talk/assets/26916108/733dd792-b134-4152-aeda-893825b5f735)

希望能够同时给一个“提交”或“确认”的蓝色按钮在删除右边，因为我感觉这样整体操作逻辑会更统一一点（已经无数次习惯性误点了……）。

虽说有一点属于我**个人**操作习惯的**问题**，但是还是觉得这样会好一些。

**Comment by logchan** [comment]
确实，我感觉加上确认、取消，然后把删除移到另一边会好点

我也不知道当时为啥做成这样了（）
