### ISSUE TITLE
移动端奇怪的对话内容编辑行为

### ISSUE THREAD

**Issue by meeboo3** [ClosureTalk/closure-talk#32]
## 现状阐述

对于已有对话内容的编辑，移动端呈现了如下奇怪的逻辑

 - 点击对话
 - 将输入聚焦至该对话
 - 再次点击该对话
 - 取消聚焦
 - 第三次点击时，出现了奇怪的行为
 - 输入聚焦至该对话，**并且弹出编辑对话内容**

后续行为
 
 - 第四次点击
 - 取消聚焦
 - 第五次点击
 - （效果与第三次点击相同）

很奇怪的逻辑，一般预期的行为是聚焦该对话，然后有某些行为可以直接编辑此对话

## 建议

聚焦对话后，在对话下方分割线处加上`编辑`样式文本，点击文本(范围可扩大至分割线)即可直接编辑，而无需三次点击

```text
e.g. (已聚焦至对话内容1)

对话内容1
---------编辑
对话内容2
对话内容3
````

**Comment by logchan** [comment]
非常好建议

分割线是指之后的对话在此处插入，另一种选择是点击后直接弹出编辑，但是编辑框里给一个按钮设置插入位置

区别就是编辑和设置插入点有一个会需要两步，你觉得哪个用得多？

**Comment by meeboo3** [comment]
直接编辑，编辑框中选择插入位置

毕竟顺序编辑为多

**Comment by logchan** [comment]
移动端逻辑已改为：点击后弹出编辑，可以在编辑框中设置插入位置
