### ISSUE TITLE
人物列表无法显示

### ISSUE THREAD

**Issue by 33homo1** [ClosureTalk/closure-talk#33]
！[上传DB551D20-9C24-4915-9A5C-2F12CA3EC403.png...]()
关于无法显示人物问题

**Comment by logchan** [comment]
图片打不开，可以重新上传一下吗

**Comment by 33homo1** [comment]
问题已经解决只需要把手机屏幕旋转一下就能看到人物列表了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月26日 05:57 |
| 收件人 | ClosureTalk/closure-talk ***@***.***> |
| 抄送人 | 33homo1 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ClosureTalk/closure-talk] 人物列表无法显示 (Issue #33) |

图片打不开，可以重新上传一下吗
