### ISSUE TITLE
Momotalk font issue

### ISSUE THREAD

**Issue by AemonJape** [ClosureTalk/closure-talk#34]
The font used for Momotalk currently is not the font used in-game.
Currently, my browser defaults to Ubuntu or sans-serif.

The web font 'GyeonggiTitle' should be used for rendering Korean MomoTalk, as it is the font used in-game.
Other languages should default to the 'Noto Sans' series.

This change would greatly help immersion with the messages.

**Comment by logchan** [comment]
Thanks for the suggestions, I have set Korean font to GyeonggiTitle (from https://github.com/webfontworld/gyeonggi).

For other languages, I'll update them when I figure out their in-game fonts.
