### ISSUE TITLE
关于明日方舟风格的段分隔符的小建议

### ISSUE THREAD

**Issue by wengsy150943** [ClosureTalk/closure-talk#4]
非常感谢您开发这样一个有趣的工具，给我的日常生活增添了许多乐趣。作为一个程序员，我也fork了您的源码学习了一番。

在学习源码的过程中，我发现明日方舟的段分隔符，也即模仿肉鸽月度小队通讯的header，在当前实现中是写死为Part.01的。当多次使用分隔符时，会稍显奇怪。或许使header的序号依次递增会显得更自然一点。不知道是否存在这样的需求？

我也尝试对源码进行了一些调整以实现这个功能。如果修改这个部分不会影响您的开发计划，且这个修改您觉得合适。我可否可以申请pr将我的修改合并进主分支中？

期待您的回复。

另，请问这个项目是否欢迎类似这样优化/修改功能的pr？不知道这样的pr是否会打乱开发计划。

**Comment by logchan** [comment]
谢谢你的喜欢和支持！我最近在外地，没有开发和merge PR的时间和环境，要到8月中旬才能继续开发。

你可以随时发PR，等我可以继续写了我可能会先处理merge减少冲突或者重复劳动。
